# Tempo para expirar o combate (em segundos)
expire-time: 20

# Caso queira que staffs não entrem em combate deixe a opção abaixo em true
staff-bypass:
  enable: false
  # Permissão necessaria para ignorar o combate
  permission: "combatlog.bypass"

# Sistema simples de punição caso o jogador deslogue em combate essa função será chamada
punish:
  # Caso esteja true o jogador morrerá ao deslogar em combate
  enable: true

# Lista de comandos que será bloqueado
command:
  enable: true
  #
  # WHITELIST - comandos são liberados em combate
  # BLACKLIST - comandos são bloqueados em combate
  restriction: BLACKLIST
  commands:
    - '/spawn'

# Lista de mundos aonde o plugin irá funcionar
worlds-block:
  enable: false
  list:
    - 'world'

pvp-timer:
  enable: false
  plot-world: "plot"